name: Build CSS from SCS

on:
  push:
    branches: [ main ]

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git source branch
        uses: actions/checkout@master

      - name: Make destnation directory for compiled CSS
        run: mkdir -vp /tmp/css

      - name: Compile SCSS files to CSS
        uses: gha-utilities/sass-build@v0.4.9
        with:
          source: |
            src/scss/loader.scss
            src/scss/menu.scss
            src/scss/style.scss
          destination: |
            /tmp/css/loader.css
            /tmp/css/menu.css
            /tmp/css/style.css

      - name: Checkout destination Git branch
        uses: actions/checkout@v2
        with:
          ref: deploy
          fetch-depth: 1

      - name: Move compiled CSS to path within deploy branch
        run: mv /tmp/css/* src/css/

      - name: Add and Commit changes to deploy branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add -f .
          git rm src/scss/
          git rm tmp/
          git commit -m 'Updated compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: deploy
      
      - name: Debug for me
        run: ls