name: Build SCSS & TypeScript, then deploy to Firebase

on:
  push:
    branches: [ main ]

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git source branch
        uses: actions/checkout@master

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/css

      - name: Compile SCSS files to CSS
        uses: gha-utilities/sass-build@v0.4.9
        with:
          source: |
            src/scss/loader.scss
            src/scss/menu.scss
            src/scss/style.scss
          destination: |
            /tmp/css/loader.css
            /tmp/css/menu.css
            /tmp/css/style.css

      - name: Upload CSS folder as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: css_folder
          path: /tmp/css/
  
  build_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git source branch
        uses: actions/checkout@master

      - name: Install node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      
      - name: Install tsc
        run: npm install -g typescript

      - name: Compile TypeScript
        run: tsc

      - name: Upload JS folder as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: js_folder
          path: src/js/

  deploy:
    needs: [ build_css, build_js ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout git source branch
        uses: actions/checkout@master

      - name: Download CSS folder artifact
        uses: actions/download-artifact@v3
        with:
          name: css_folder

      - name: Download JS folder artifact
        uses: actions/download-artifact@v3
        with:
          name: js_folder

      - name: List files
        run: ls -R

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
#  
#  http_request:
#    needs: deploy
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Make Request
#        id: request
#        uses: fjogeleit/http-request-action@v1
#        with:
#          url: "http://yoursite.com/api"